config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :welcome
  resources :projects do
    collection do 
      get 'project2'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

	def graph_type_link(graph_type,title,label_y)
		if graph_type == "GroundWater"
			markers = @markers_GroundWater
			data = @data
		elsif graph_type == "Distance"
		    markers = @markers_Distance
		    data = @data
		elsif graph_type == "Rainfall"
		    markers = @markers_Rainfall
		    data = @data
		else
			data = @data_Day
		end

		unless params[:graph_type]==graph_type.to_s
			link_to title.to_s,"#/",
			data:{
				data_for_graph:data, 
				graph_type:graph_type.to_s,
				title:title.to_s,
				label_y:label_y
			},
			class:"btn btn-info btn-change-graph-type",
			id:graph_type.to_s
		else
			link_to title.to_s,"#/",
			data:{
				data_for_graph:data, 
				graph_type:graph_type.to_s,
				title:title.to_s,
				label_y:label_y
			},
			class:"btn btn-primary btn-change-graph-type",
			id:graph_type.to_s
		end
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="bg-black" id="footer" style="height:80px;">
	<div class="container" id="nav">
		<div class="row">
			<div class="col-md-12 text-right" style="">
				<%= image_tag("12.png", :alt => "12",id:"logo",height:"30") %>
				<%= link_to "Group12",welcome_index_path ,class:"font-white",id:"group-name" %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_nav.html.erb
<div class="bg-black" id="nav-black">
	<div class="container" id="nav">
		<div class="row">
			<div class="col-xs-4" style="">
				<%= image_tag("12.png", :alt => "12",id:"logo",height:"30") %>
				<%= link_to "Group12",welcome_index_path ,class:"font-white",id:"group-name" %>
			</div>
			<div class="col-xs-8 text-right font-14">
				<%= link_to "Projects",projects_path ,class:"btn  font-white " %>
				<%= link_to "Members",projects_path ,class:"btn  font-white " %>
				<%= link_to "Home",welcome_index_path ,class:"btn  font-white " %>
			</div>
		</div>
	</div>
</div>
<div id="nav-mobile-menu-btn">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-right font-white">
				<%= image_tag("mobile_menu_icon.png", :alt => "mobile_menu_icon",id:"logo",width:"50") %>
			</div>
		</div>
	</div>
</div>

<div class="bg-black" id="nav-mobile" style="">
	<div class="">
		<div class="row">
			<!-- <div class="col-xs-8 col-xs-offset-2 font-white" id="btn-nav-mobile">
				Group12
			</div> -->
			<div class="col-xs-10 col-xs-offset-2 text-right bd-right-black btn-nav-mobile" id="btn-close-mobile-menu" style="padding-right:120px;">
				<%= image_tag("mobile_menu_close_icon.png", :alt => "mobile_menu_close_icon",id:"logo",width:"50") %>
			</div>
			
			<%= link_to welcome_index_path ,class:"btn-nav-mobile-link font-white" do %>
				<div class="col-xs-12 bd-right-red btn-nav-mobile font-white" ,data-color="#E8837E"}>
					Home
				</div>
			<% end %>
			<%= link_to projects_path ,class:"btn-nav-mobile-link font-white" do %>
				<div class="col-xs-12 bd-right-blue btn-nav-mobile font-white" ,data-color="#ACBA9A"}>
					Project
				</div>
			<% end %>
			<%= link_to projects_path ,class:"btn-nav-mobile-link font-white" do %>
				<div class="col-xs-12 bd-right-green btn-nav-mobile font-white" ,data-color="#749D9B"}>
					Members
				</div>
			<% end %>
			<div class="col-xs-10 col-xs-offset-2 bd-right-black text-left font-white btn-nav-mobile" id="btn-close-mobile-menu">
				&nbsp
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Datavisualize</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Arvo">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Source Sans Pro">
</head>
<body>
  	<%= render 'layouts/nav' %>
  <%= yield %>
    <%= render 'layouts/footer' %>
</body>
</html>